# Configuration file for how to "build" our package.
#
# https://www.python.org/dev/peps/pep-0517/
# https://setuptools.readthedocs.io/en/latest/build_meta.html

[build-system]
requires = [
  "setuptools>=40.9.0",
  "wheel",
]
build-backend = "setuptools.build_meta"
